spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/super_market?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN